export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_FAILURE = "LOGIN_FAILURE";
export const APPLICANT_SIGNUP_SUCCESS = "APPLICANT_SIGNUP_SUCCESS";
export const APPLICANT_SIGNUP = "APPLICANT_SIGNUP";
export const RECRUITER_SIGNUP_SUCCESS = "RECRUITER_SIGNUP_SUCCESS";
export const SIGNUP_FAILURE = "SIGNUP_FAILURE";
